### ISSUE TITLE
大神怎么调用呀

### ISSUE THREAD

**Issue by HAdesblog** [ChinaSilence/micro-node-douyin#2]
我运行server.js开启6565端口之后怎么操纵呀。。。。

**Comment by ningj123** [comment]
同求怎么调用

**Comment by ChinaSilence** [comment]
原理：[使用 NodeJS 提供抖音签名算法服务](https://www.jianshu.com/p/43c10df00be3)

要直接运行我在 github 上提供的源码比较复杂，暂时没空提供相关文档，大致技术方向: nodejs/grpc/spring boot

**Comment by y2kbug-hk** [comment]
May I know what method or parameter should I call from the Python client side?
"handle()"?

> import service_pb2_grpc
        with grpc.insecure_channel('updater-tiktok-sign:6565') as channel:
            stub = tiktok_service_pb2_grpc.CommonServiceStub(channel)
            signature = stub.handle(USER_ID)
            print(signature)

**Comment by y2kbug-hk** [comment]
May I know what method or parameter should I call from the Python client side?
handle() ?

> import service_pb2_grpc
        with grpc.insecure_channel('nodejs:6565') as channel:
            stub = service_pb2_grpc.CommonServiceStub(channel)
            signature = stub.handle(USER_ID)
            print(signature)

**Comment by wangxiaoran1995** [comment]
现在不能用了吗？

**Comment by davidblus** [comment]
这样计算出的_signature是不是无法保证每次请求都有数据呀？我发现需要重试好多次才能成功获取到一次数据。

**Comment by FENG1000** [comment]
> 这样计算出的_signature是不是无法保证每次请求都有数据呀？我发现需要重试好多次才能成功获取到一次数据。

大佬，请教下这个项目启动后要如何调用啊

**Comment by ChinaSilence** [comment]
目前我这边请求是 100% 能拿到数据

**Comment by ChinaSilence** [comment]
@wangxiaoran1995 有的，最近有更新

**Comment by zxdmrg** [comment]
> @HAdesblog  @同求怎么调用
可以看下这里
https://github.com/zxdmrg/douyin_signature

**Comment by zxdmrg** [comment]
@davidblus  你应该是没有使用tac参数.这个每次都会变的

**Comment by hpsfpcca** [comment]
同求怎么调用,
