### ISSUE TITLE
params

### ISSUE THREAD

**Issue by DeOne4eg** [ChinaSilence/micro-node-douyin#4]
Hello. Tell me, please, what does the function generateSignature expect as parameters? As I understand it, it should be an array in which the null parameter is userId, but what is expected in the first index? What code should the eval () function execute? I tried to leave the parameter empty (args: ["96956380265", ""]), but signature still doesn't work. Thanks.

你好 请告诉我，函数generateSignature期望作为参数吗？ 据我了解，它应该是一个null参数为userId的数组，但是第一个索引应该是什么？ eval（）函数应执行什么代码？ 我试图将参数保留为空（参数：[“ 96956380265”，“”]），但是签名仍然不起作用。 谢谢啦

**Comment by ChinaSilence** [comment]
For example:
```
["96956380265", "tac='i)69k7yhzujs!i$181ns"0,<8~z|\x7f@QGNCJF[\\^D\\KFYSk~^WSZhg,(lfi~ah`{md"inb|1d<,%Dscafgd"in,8[xtm}nLzNEGQMKAdGG^NTY\x1ckgd"inb<b|1d<g,&TboLr{m,(\x02)!jx-2n&vr$testxg,%@tug{mn ,%vrfkbm[!cb|'"]
```

the second param is available from html
